version: '3.2'

services:

# -----------------------------------------------------------
# SolrWayback
# -----------------------------------------------------------

  solrwayback:
    build:
      context: .
      args:
        - "http_proxy=${HTTP_PROXY}"
        - "https_proxy=${HTTPS_PROXY}"
    ports:
      - "8085:8080"
    environment: 
      - "SOLR_URL=http://solr:8983/solr/discovery"

