version: '3.2'

services:

# -----------------------------------------------------------
# SolrWayback
# -----------------------------------------------------------

  solrwayback:
    build:
      context: .
      args:
        - "http_proxy=${HTTP_PROXY}"
        - "https_proxy=${HTTPS_PROXY}"
        - "MAVEN_OPTS=${MAVEN_OPTS}"
    ports:
      - "8085:8080"
    environment: 
      - "SOLR_URL=${SOLR_URL:-http://solr:8983/solr/discovery}"

  # Solr instance for running tests against
  solr:
    image: ukwa/webarchive-discovery-solr:master
    ports:
      - "18983:8983"

  # Hook to populate the image with test data:
  populate:
    image: ukwa/webarchive-discovery-solr:master
    command: "/populate.sh"
    environment:
      - "SOLR_URL=${SOLR_URL:-http://solr:8983/solr/discovery}"


